bool str_eq(const char*, const char*);
bool test_c_str(string&);
bool test_size(string&, int);
bool test_clear(string&);
bool test_eq_char(string&, char);
bool test_addition();
bool test_length();
bool test_maxsize();
bool test_capacity();
bool test_empty();
bool test_reserve();
bool test_eq_cstr();
bool test_plus_2str();
bool test_resize();
