bool str_eq(const char*, const char*);
bool test_c_str();
bool test_size();
bool test_clear();
bool test_eq_char();
bool test_addition();
bool test_length();
bool test_maxsize();
bool test_capacity();
bool test_empty();
bool test_reserve();
bool test_eq_cstr();
bool test_plus_2str();
bool test_resize();
bool test_op_eq_str();
