bool str_eq(const char*, const char*);
const char* test_c_str();
const char* test_size();
const char* test_clear();
const char* test_eq_char();
const char* test_addition();
const char* test_length();
const char* test_maxsize();
const char* test_capacity();
const char* test_empty();
const char* test_reserve();
const char* test_eq_cstr();
const char* test_plus_2str();
const char* test_resize();
const char* test_op_eq_str();
const char* test_op_plus_char();
